language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  
before_script:
  - chmod a+x scripts/unix/travis.sh
  - chmod a+x scripts/unix/tests.sh
  - ./scripts/unix/travis.sh
  
script: 
  - ./scripts/unix/tests.sh
