language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  
before_script:
  - chmod -R 777 ./scripts/setUp.sh
  - ./scripts/setUp.sh
  
script: 
  - 'php tests/phpUnit.php --configuration tests/phpUnit/config.xml tests/'
